import json
from pathlib import Path

import pytest

from signalbench.ingest.cdr import (
    CdrEntry,
    build_entries,
    diff_universe,
    dump_universe,
    gics_sector,
    load_universe,
    parse_cboe_directory,
)

FIXTURES = Path(__file__).parent / "fixtures"


def _payload() -> dict[str, object]:
    return json.loads((FIXTURES / "cboe_directory.json").read_text(encoding="utf-8"))


def _nvda() -> CdrEntry:
    return CdrEntry(
        us_symbol="NVDA",
        cdr_symbol="ZNVD",
        price_symbol="ZNVD.NE",
        company_name="Nvidia",
        sector="Information Technology",
    )


def test_parse_keeps_us_company_drs_only() -> None:
    listings = parse_cboe_directory(_payload())
    assert [(item.us_symbol, item.cdr_symbol) for item in listings] == [
        ("BRK-B", "ZBRK"),
        ("MCD", "ZMCD"),
        ("NVDA", "ZNVD"),
    ]


def test_company_names_are_capwords() -> None:
    names = {item.us_symbol: item.company_name for item in parse_cboe_directory(_payload())}
    assert names["NVDA"] == "Nvidia"
    assert names["MCD"] == "Mcdonald's"
    assert names["BRK-B"] == "Berkshire Hathaway"


def test_parse_rejects_two_cdrs_for_one_us_symbol() -> None:
    payload = {
        "data": [
            {"symbol": "ZNVD", "name": "NVIDIA (NVDA) BMO CDR (CAD HEDGED)", "security": "dr"},
            {"symbol": "NVDA", "name": "NVIDIA (NVDA) CIBC CDR (CAD HEDGED)", "security": "dr"},
        ]
    }
    with pytest.raises(ValueError, match="NVDA"):
        parse_cboe_directory(payload)


def test_gics_mapping() -> None:
    assert gics_sector("Technology") == "Information Technology"
    assert gics_sector("Consumer Cyclical") == "Consumer Discretionary"
    with pytest.raises(ValueError, match="Crypto"):
        gics_sector("Crypto")


def test_build_entries_reuses_known_sectors_and_looks_up_new_ones() -> None:
    calls: list[str] = []

    def lookup(symbol: str) -> str:
        calls.append(symbol)
        return "Financials"

    entries = build_entries(parse_cboe_directory(_payload()), lookup, existing=[_nvda()])
    by_symbol = {entry.us_symbol: entry for entry in entries}
    assert calls == ["BRK-B", "MCD"]
    assert by_symbol["NVDA"].sector == "Information Technology"
    assert by_symbol["BRK-B"].price_symbol == "ZBRK.NE"
    assert by_symbol["MCD"].sector == "Financials"


def test_yaml_round_trip(tmp_path: Path) -> None:
    path = tmp_path / "universe.yaml"
    dump_universe([_nvda()], path)
    assert load_universe(path) == [_nvda()]
    assert path.read_text(encoding="utf-8").startswith("# Generated by")


def test_dump_creates_missing_parent_directory(tmp_path: Path) -> None:
    path = tmp_path / "data" / "universe.yaml"
    dump_universe([_nvda()], path)
    assert load_universe(path) == [_nvda()]


def test_load_rejects_duplicate_us_symbols(tmp_path: Path) -> None:
    path = tmp_path / "universe.yaml"
    dump_universe([_nvda(), _nvda()], path)
    with pytest.raises(ValueError, match="NVDA"):
        load_universe(path)


def test_diff_universe() -> None:
    aapl = CdrEntry(
        us_symbol="AAPL",
        cdr_symbol="ZAAP",
        price_symbol="ZAAP.NE",
        company_name="Apple",
        sector="Information Technology",
    )
    diff = diff_universe([_nvda(), aapl], parse_cboe_directory(_payload()))
    assert [item.us_symbol for item in diff.added] == ["BRK-B", "MCD"]
    assert [entry.us_symbol for entry in diff.removed] == ["AAPL"]
